name: india_club
description: A new Flutter project.

publish_to:


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.4
  google_fonts: ^5.1.0
  iconly: ^1.0.1
  intl: ^0.18.1
  flutter_svg: ^2.0.7
  m_toast: ^0.2.2
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  carousel_slider: ^4.2.1
  date_picker_timeline: ^1.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  assets:
    - assets/images/


